spring:
  application:
    name: service-sys
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
        group: DEV_GROUP
        namespace: dev
        username: admin
        password: admin